version: '3'
 
services:

  mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: 019638
    ports:
      - 6033:3306
    volumes:
      - mysqldata:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5
    links:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
    ports:
      - 8080:80

volumes:
  mysqldata: