version: '3'

services:
  mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: 019638
    ports:
      - 6033:3306
    volumes:
      - mysqldata:/var/lib/mysql

volumes:
  mysqldata:      